id: I78FA8287
legacy_id: P010558
ocr_import_info:
  bdrc_scan_id: W4CZ30835
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T18:02:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T13:00:04.218326+00:00'
last_modified: 2022-08-27 21:01:10.950843
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ30835
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ30835
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དབང་ཆེན་དགྱེས་རབ་རྡོ་རྗེ།
  author: དབང་ཆེན་དགྱེས་རབ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9625810077464473
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I4CZ30838:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ30838
      total_pages: 324
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4CZ30838.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9615843678188192
    legacy_id: v002
  I4CZ30839:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ30839
      total_pages: 372
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4CZ30839.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9585709983844434
    legacy_id: v003
  I4CZ30837:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ30837
      total_pages: 317
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ30837.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9665408415352851
    legacy_id: v001
  I4CZ30841:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ30841
      total_pages: 388
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4CZ30841.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9607898728427615
    legacy_id: v005
  I4CZ30840:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ30840
      total_pages: 408
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4CZ30840.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9656123281895127
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
